### ISSUE TITLE
Error when trying to send a snippet

### ISSUE THREAD

**Issue by nadavkaner** [verydanny/vcslack#3]
Hey, 
I followed over the steps and put the slack legacy key in my settings.json, but when trying to send a snippet by selecting "VCSlack: Send Snippet" from the command palette i'm getting this error: "command 'vcslack.sendSnippet' not found".

**Comment by jrdnmdhl** [comment]
I also experience this error when trying to send a snippet.

**Comment by verydanny** [comment]
@nadavkaner 
@jrdnmdhl 

I suspect this is a dependency issue, mistake on my part.

1. Can you open developer tools (Help -> Toggle Developer Tools)
2. Run the command again
3. See if there's an error in the dev tools, and if there is, copy it here

**Comment by verydanny** [comment]
> Hey,
> I followed over the steps and put the slack legacy key in my settings.json, but when trying to send a snippet by selecting "VCSlack: Send Snippet" from the command palette i'm getting this error: "command 'vcslack.sendSnippet' not found".

> I also experience this error when trying to send a snippet.

Fixed #4
